/*
 * PID_Industrial_Simulator Copyright Batzonis Constantinos
 */
package ui;

/**
 *
 * @author dinob
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainBackgroundPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        setupMenu = new javax.swing.JMenu();
        connectionMenu = new javax.swing.JMenuItem();
        modeSelectionMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout mainBackgroundPanelLayout = new javax.swing.GroupLayout(mainBackgroundPanel);
        mainBackgroundPanel.setLayout(mainBackgroundPanelLayout);
        mainBackgroundPanelLayout.setHorizontalGroup(
            mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1056, Short.MAX_VALUE)
        );
        mainBackgroundPanelLayout.setVerticalGroup(
            mainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        getContentPane().add(mainBackgroundPanel, java.awt.BorderLayout.CENTER);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ui/Bundle"); // NOI18N
        setupMenu.setText(bundle.getString("MainMenu.setupMenu.text")); // NOI18N
        setupMenu.setToolTipText(bundle.getString("MainMenu.setupMenu.toolTipText")); // NOI18N

        connectionMenu.setText(bundle.getString("MainMenu.connectionMenu.text")); // NOI18N
        setupMenu.add(connectionMenu);

        modeSelectionMenu.setText(bundle.getString("MainMenu.modeSelectionMenu.text")); // NOI18N
        setupMenu.add(modeSelectionMenu);
        setupMenu.add(jSeparator1);

        exitMenu.setText(bundle.getString("MainMenu.exitMenu.text")); // NOI18N
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        setupMenu.add(exitMenu);

        menuBar.add(setupMenu);

        jMenu2.setText(bundle.getString("MainMenu.jMenu2.text")); // NOI18N
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem connectionMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPanel mainBackgroundPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem modeSelectionMenu;
    private javax.swing.JMenu setupMenu;
    // End of variables declaration//GEN-END:variables
}
